### ISSUE TITLE
[question] - is the reamde.md up to date?

### ISSUE THREAD

**Issue by macchmie3** [rebus-org/Rebus.SimpleInjector#12]
After bumping Rebus.SimpleInjector from 7.0.0 to 8.0.0 container.ConfigureRebus is no longer found.

**Comment by mookid8000** [comment]
Looks like it's not uptodate 😐 

Take a look here for an API example that compiles: https://github.com/rebus-org/Rebus.SimpleInjector/blob/master/Rebus.SimpleInjector.Tests/CheckRegistrationApi.cs 😅 

I'll fix it one of the coming days (unless you send a PR 😉 )

**Comment by macchmie3** [comment]
@mookid8000  https://github.com/rebus-org/Rebus.SimpleInjector/pull/13 :)
