### ISSUE TITLE
Rebus.SimpleInjector does not support polymorphic dispatch

### ISSUE THREAD

**Issue by MrMDavidson** [rebus-org/Rebus.SimpleInjector#3]
Just a heads up... the implementation of `SimpleInjectorAdapter` does not support polymorphic dispatch. If you have `CustomerCreatedEvent` -> `BaseCustomerEvent` -> `Event` then handlers for `BaseCustomerEvent` and `Event` would not ever be invoked. In particular this breaks second level retries as the container attempts to resolve a `Rebus.Retry.Simple.FailedMessageWrapper<TMessageType>` which is a private class and thus cannot ever be implemented by consumers of the Rebus library. (They'd instead be implementing an `IHandleMessages<IFailed<TMessageType>>`.

The offending code is https://github.com/rebus-org/Rebus.SimpleInjector/blob/master/Rebus.SimpleInjector/SimpleInjectorContainerAdapter.cs#L56. If you contrast this to your other IoC libraries you'll note they get the base types and enumerate the base types and resolve the handlers for each type. Eg.
https://github.com/rebus-org/Rebus.CastleWindsor/blob/master/Rebus.CastleWindsor/Config/CastleWindsorContainerAdapter.cs#L111

Given this needs to be implemented in every container implementation I wonder if it's worth while providing a base / helper class for this in Rebus core.

```C#
public class BaseContainerAdapter : IContainerAdapter {
  public virtual async Task<IEnumerable<IHandleMessages<TMessage>>> GetHandlers<TMessage>(TMessage message, ITransactionContext transactionContext) {
    Type openMessageType = typeof(IHandleMessages<>);
    return GetMessageTypes(message)
      .SelectMany(type => GetHandlersForType(type))
      .ToList();
  }

  protected abstract Task<IEnumerable<Type>> GetHandlersForType(TMessage type, ITransactionContext transactionContext);

  protected IEnumerable<Type> GetMessageTypes<TMessageType>(TMessageType message) {
    return typeof(TMessageType).GetBaseTypes()
      .Concat(new [] { typeof(TMessageType) } )
      .ToList();
  }
}
```

This way if a specific IoC supported resolving for all derived types automatically an implementer could just override `GetHandlers`. Otherwise they can just implement `GetHandlersForType` and only need to worry about resolving for the given type (Eg. `CustomerCreatedEvent`, `BaseCustomerEvent`, `Event` each time its called).

Note: The `BaseContainerAdapter` class was written straight into the GitHub issue so likely isn't perfect but I'm sure you get the idea :)

**Comment by mookid8000** [comment]
Damn.. I have to investigate, because [this test case](https://github.com/rebus-org/Rebus/blob/f1a50e94f1a1624512e83fbcc62464d767ef3ac1/Rebus.Tests.Contracts/Activation/ContainerTests.cs#L303-L317) attempts to verify that polymorphic dispatch works as it should, but apparently it works differently with SimpleInjector when interfaces are involved.

I'll be back 😄

**Comment by MrMDavidson** [comment]
Interesting. I'll try and find some time to provide a simple test case at work today. We were definitely having 2nd level retry messages not getting delivered. The fix was to iterate the base types of the message and attempting to resolve handlers for each base type.
________________________________

**Comment by mookid8000** [comment]
I already added [this test](https://github.com/rebus-org/Rebus/blob/f0edb2e565ac0e3c5b0539f59e4d0046efc133dc/Rebus.Tests.Contracts/Activation/ContainerTests.cs#L304-L321) to the Rebus.Tests.Contracts package, so updating it to 4.2.0 should bring it in

**Comment by mookid8000** [comment]
weird – I brought in the test, but it seems to work like it should....

the symptoms you are experiencing – could it be something with how you register your handler type?

**Comment by MrMDavidson** [comment]
I think you're right; it is how we're doing the registration. We're using 2.x of SimpleInjector, for legacy reasons, and `RegisterManyForOpenGeneric` to perform our `IHandleMessages<>` registration. I know in 3.x they deprecated / removed `RegisterManyForOpenGeneric` (See: https://simpleinjector.org/blog/2015/08/simple-injector-v3-is-here/ ). For us the fix was to re-implement the `SimpleInjectorContainerAdapter` and iterate the base types of `TMessage` when resolving the handlers in `GetHandlers<TMessage>(...)`.

**Comment by mookid8000** [comment]
Hey @MrMDavidson did you figure out if it was your registrations that caused the problem?

**Comment by MrMDavidson** [comment]
I'm fairly confident it is but haven't been able to narrow it down to an exact repro case. Given how old a version of SimpleInjector we're on I'm happy to just close this.

**Comment by mookid8000** [comment]
I'm closing this 😁
