### ISSUE TITLE
Can't call the container.ConfigureRebus() extension method.

### ISSUE THREAD

**Issue by danilobreda** [rebus-org/Rebus.SimpleInjector#5]
Im having a lot of trouble to configure the simpleinjector with the rebus, on a asp net core 2.0 project (webapi).

The extension method seems to be lost.

![image](https://user-images.githubusercontent.com/14843499/39009321-a8302444-43e1-11e8-86f6-cd020accbce0.png)

Rebus 4.2.1
SimpleInjector 4.2.1
Rebus.SimpleInjector 4.0.0

Help me @mookid8000

**Comment by mookid8000** [comment]
that's weird – I've release a new package (version 5.0.0-b02) with an explicit target for .NET Standard 2.0 – could you try and see if that works better for you?

**Comment by danilobreda** [comment]
With Rebus 5.0.0-b08 and Rebus.SimpleInjector 5.0.0-b02 the ConfigureRebus method is showing(problem resolved), but i have no access to the Adapter (SimpleInjectorContainerAdapter.cs), is that ok?

**Comment by mookid8000** [comment]
Yes, that’s intentional – it’s to avoid confusing people, so they don’t accidentally think that the adapter should be configured the old way. 

Sendt fra min iPhone

–
Mogens Heller Grabe
Torsmark 4
8700 Horsens
Danmark

+45 29367077
mookid8000@gmail.com
